// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrganization = "colab_organization"

// Organization 组织表
type Organization struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Name        string         `gorm:"column:name;type:varchar(255);not null;comment:名称" json:"name"`           // 名称
	Avatar      *string        `gorm:"column:avatar;type:varchar(500);comment:头像" json:"avatar"`                // 头像
	Description *string        `gorm:"column:description;type:varchar(500);comment:描述" json:"description"`      // 描述
	Owner       int64          `gorm:"column:owner;type:bigint;not null;comment:拥有者" json:"owner"`              // 拥有者
	Personal    bool           `gorm:"column:personal;type:tinyint(1);not null;comment:是否个人项目" json:"personal"` // 是否个人项目
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
