// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEntityAttribute = "colab_entity_attribute"

// EntityAttribute mapped from table <colab_entity_attribute>
type EntityAttribute struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Biz         string         `gorm:"column:biz;type:varchar(16);not null;uniqueIndex:colab_entity_attribute_uindex,priority:1" json:"biz"`
	BizID       int64          `gorm:"column:biz_id;type:bigint;not null;uniqueIndex:colab_entity_attribute_uindex,priority:2" json:"biz_id"`
	Code        string         `gorm:"column:code;type:varchar(32);not null;uniqueIndex:colab_entity_attribute_uindex,priority:3" json:"code"`
	Value       string         `gorm:"column:value;type:varchar(255);not null" json:"value"`
	DisplayName string         `gorm:"column:display_name;type:varchar(255);not null" json:"display_name"`
}

// TableName EntityAttribute's table name
func (*EntityAttribute) TableName() string {
	return TableNameEntityAttribute
}
