// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrganizationMember = "colab_organization_member"

// OrganizationMember 组织成员表
type OrganizationMember struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	OrgID     int64          `gorm:"column:org_id;type:bigint;not null;comment:组织ID" json:"org_id"`               // 组织ID
	UserID    int64          `gorm:"column:user_id;type:bigint;not null;comment:成员ID" json:"user_id"`             // 成员ID
	IsOwner   bool           `gorm:"column:is_owner;type:tinyint(1);not null;comment:是否是组织owner" json:"is_owner"` // 是否是组织owner
}

// TableName OrganizationMember's table name
func (*OrganizationMember) TableName() string {
	return TableNameOrganizationMember
}
