// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "colab_user"

// User mapped from table <colab_user>
type User struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Username  string         `gorm:"column:username;type:varchar(64);not null;uniqueIndex:colab_user_username_uindex,priority:1" json:"username"`
	Password  string         `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Email     string         `gorm:"column:email;type:varchar(64);not null;uniqueIndex:colab_user_email_uindex,priority:1" json:"email"`
	Mobile    string         `gorm:"column:mobile;type:varchar(16);not null;uniqueIndex:colab_user_mobile_uindex,priority:1" json:"mobile"`
	Nickname  string         `gorm:"column:nickname;type:varchar(64);not null" json:"nickname"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
