// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAttributeItem = "colab_attribute_item"

// AttributeItem mapped from table <colab_attribute_item>
type AttributeItem struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Code      string         `gorm:"column:code;type:varchar(32);not null;uniqueIndex:colab_attribute_item_code_uindex,priority:1" json:"code"`
	Label     string         `gorm:"column:label;type:varchar(32);not null" json:"label"`
	Component string         `gorm:"column:component;type:varchar(32);not null" json:"component"`
	Props     *string        `gorm:"column:props;type:json" json:"props"`
	Status    string         `gorm:"column:status;type:varchar(32);not null" json:"status"`
}

// TableName AttributeItem's table name
func (*AttributeItem) TableName() string {
	return TableNameAttributeItem
}
