// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: portal/portal_menu_srv.proto

package portal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMenuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserMenuRequest) Reset() {
	*x = UserMenuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_portal_menu_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMenuRequest) ProtoMessage() {}

func (x *UserMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_portal_menu_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMenuRequest.ProtoReflect.Descriptor instead.
func (*UserMenuRequest) Descriptor() ([]byte, []int) {
	return file_portal_portal_menu_srv_proto_rawDescGZIP(), []int{0}
}

type UserMenuItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int64           `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Title         string          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string          `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Url           string          `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Filepath      string          `protobuf:"bytes,6,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Params        string          `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Node          string          `protobuf:"bytes,8,opt,name=node,proto3" json:"node,omitempty"`
	Sort          int32           `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32           `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	IsInner       bool            `protobuf:"varint,11,opt,name=isInner,proto3" json:"isInner,omitempty"`
	DefaultValues string          `protobuf:"bytes,12,opt,name=defaultValues,proto3" json:"defaultValues,omitempty"`
	ShowSlider    bool            `protobuf:"varint,13,opt,name=showSlider,proto3" json:"showSlider,omitempty"`
	StatusText    string          `protobuf:"bytes,14,opt,name=statusText,proto3" json:"statusText,omitempty"`
	InnerText     string          `protobuf:"bytes,15,opt,name=innerText,proto3" json:"innerText,omitempty"`
	FullUrl       string          `protobuf:"bytes,16,opt,name=fullUrl,proto3" json:"fullUrl,omitempty"`
	Children      []*UserMenuItem `protobuf:"bytes,17,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *UserMenuItem) Reset() {
	*x = UserMenuItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_portal_menu_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMenuItem) ProtoMessage() {}

func (x *UserMenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_portal_portal_menu_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMenuItem.ProtoReflect.Descriptor instead.
func (*UserMenuItem) Descriptor() ([]byte, []int) {
	return file_portal_portal_menu_srv_proto_rawDescGZIP(), []int{1}
}

func (x *UserMenuItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMenuItem) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UserMenuItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserMenuItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserMenuItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UserMenuItem) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *UserMenuItem) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *UserMenuItem) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *UserMenuItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UserMenuItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserMenuItem) GetIsInner() bool {
	if x != nil {
		return x.IsInner
	}
	return false
}

func (x *UserMenuItem) GetDefaultValues() string {
	if x != nil {
		return x.DefaultValues
	}
	return ""
}

func (x *UserMenuItem) GetShowSlider() bool {
	if x != nil {
		return x.ShowSlider
	}
	return false
}

func (x *UserMenuItem) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *UserMenuItem) GetInnerText() string {
	if x != nil {
		return x.InnerText
	}
	return ""
}

func (x *UserMenuItem) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *UserMenuItem) GetChildren() []*UserMenuItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type UserMenuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Menus []*UserMenuItem `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
}

func (x *UserMenuResponse) Reset() {
	*x = UserMenuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_portal_menu_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMenuResponse) ProtoMessage() {}

func (x *UserMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_portal_menu_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMenuResponse.ProtoReflect.Descriptor instead.
func (*UserMenuResponse) Descriptor() ([]byte, []int) {
	return file_portal_portal_menu_srv_proto_rawDescGZIP(), []int{2}
}

func (x *UserMenuResponse) GetMenus() []*UserMenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

var File_portal_portal_menu_srv_proto protoreflect.FileDescriptor

var file_portal_portal_menu_srv_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x5f,
	0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e,
	0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc9, 0x03, 0x0a, 0x0c, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69,
	0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x68, 0x6f, 0x77, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65, 0x78, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x75, 0x6c,
	0x6c, 0x55, 0x72, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c,
	0x55, 0x72, 0x6c, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18,
	0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x6d, 0x65,
	0x6e, 0x75, 0x73, 0x32, 0x4e, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e,
	0x75, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_portal_portal_menu_srv_proto_rawDescOnce sync.Once
	file_portal_portal_menu_srv_proto_rawDescData = file_portal_portal_menu_srv_proto_rawDesc
)

func file_portal_portal_menu_srv_proto_rawDescGZIP() []byte {
	file_portal_portal_menu_srv_proto_rawDescOnce.Do(func() {
		file_portal_portal_menu_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_portal_portal_menu_srv_proto_rawDescData)
	})
	return file_portal_portal_menu_srv_proto_rawDescData
}

var file_portal_portal_menu_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_portal_portal_menu_srv_proto_goTypes = []any{
	(*UserMenuRequest)(nil),  // 0: proto.UserMenuRequest
	(*UserMenuItem)(nil),     // 1: proto.UserMenuItem
	(*UserMenuResponse)(nil), // 2: proto.UserMenuResponse
}
var file_portal_portal_menu_srv_proto_depIdxs = []int32{
	1, // 0: proto.UserMenuItem.children:type_name -> proto.UserMenuItem
	1, // 1: proto.UserMenuResponse.menus:type_name -> proto.UserMenuItem
	0, // 2: proto.MenuService.GetUserMenus:input_type -> proto.UserMenuRequest
	2, // 3: proto.MenuService.GetUserMenus:output_type -> proto.UserMenuResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_portal_portal_menu_srv_proto_init() }
func file_portal_portal_menu_srv_proto_init() {
	if File_portal_portal_menu_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_portal_portal_menu_srv_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserMenuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_portal_menu_srv_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserMenuItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_portal_menu_srv_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UserMenuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portal_portal_menu_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portal_portal_menu_srv_proto_goTypes,
		DependencyIndexes: file_portal_portal_menu_srv_proto_depIdxs,
		MessageInfos:      file_portal_portal_menu_srv_proto_msgTypes,
	}.Build()
	File_portal_portal_menu_srv_proto = out.File
	file_portal_portal_menu_srv_proto_rawDesc = nil
	file_portal_portal_menu_srv_proto_goTypes = nil
	file_portal_portal_menu_srv_proto_depIdxs = nil
}
