// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: snowflake/snowflake_srv.proto

package snowflake

import (
	common "colab/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnowflakeID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SnowflakeID) Reset() {
	*x = SnowflakeID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snowflake_snowflake_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnowflakeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnowflakeID) ProtoMessage() {}

func (x *SnowflakeID) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_snowflake_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnowflakeID.ProtoReflect.Descriptor instead.
func (*SnowflakeID) Descriptor() ([]byte, []int) {
	return file_snowflake_snowflake_srv_proto_rawDescGZIP(), []int{0}
}

func (x *SnowflakeID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_snowflake_snowflake_srv_proto protoreflect.FileDescriptor

var file_snowflake_snowflake_srv_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x6f, 0x77,
	0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x32, 0x3e, 0x0a, 0x10, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x4e, 0x65, 0x78, 0x74, 0x49,
	0x44, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x49, 0x44, 0x42, 0x1a, 0x5a, 0x18, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snowflake_snowflake_srv_proto_rawDescOnce sync.Once
	file_snowflake_snowflake_srv_proto_rawDescData = file_snowflake_snowflake_srv_proto_rawDesc
)

func file_snowflake_snowflake_srv_proto_rawDescGZIP() []byte {
	file_snowflake_snowflake_srv_proto_rawDescOnce.Do(func() {
		file_snowflake_snowflake_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_snowflake_snowflake_srv_proto_rawDescData)
	})
	return file_snowflake_snowflake_srv_proto_rawDescData
}

var file_snowflake_snowflake_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_snowflake_snowflake_srv_proto_goTypes = []any{
	(*SnowflakeID)(nil),  // 0: proto.SnowflakeID
	(*common.Empty)(nil), // 1: proto.Empty
}
var file_snowflake_snowflake_srv_proto_depIdxs = []int32{
	1, // 0: proto.SnowflakeService.NextID:input_type -> proto.Empty
	0, // 1: proto.SnowflakeService.NextID:output_type -> proto.SnowflakeID
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snowflake_snowflake_srv_proto_init() }
func file_snowflake_snowflake_srv_proto_init() {
	if File_snowflake_snowflake_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snowflake_snowflake_srv_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SnowflakeID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snowflake_snowflake_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snowflake_snowflake_srv_proto_goTypes,
		DependencyIndexes: file_snowflake_snowflake_srv_proto_depIdxs,
		MessageInfos:      file_snowflake_snowflake_srv_proto_msgTypes,
	}.Build()
	File_snowflake_snowflake_srv_proto = out.File
	file_snowflake_snowflake_srv_proto_rawDesc = nil
	file_snowflake_snowflake_srv_proto_goTypes = nil
	file_snowflake_snowflake_srv_proto_depIdxs = nil
}
